ai_provider: grok

openai:
  api_key: ${OPENAI_API_KEY}
  model: gpt-4o-mini-2024-07-18
  max_tokens: 4096

claude:
  api_key: ${ANTHROPIC_API_KEY}
  model: claude-3-haiku-20240307
  max_tokens: 4096

grok:
  api_key: ${GROK_API_KEY}
  text_model: grok-2-latest
  vision_model: grok-2-vision-1212
  max_tokens: 4096