ai_provider: openai

openai:
  api_key: ${OPENAI_API_KEY}
  model: gpt-4o
  max_tokens: 4096
  temperature: 0.2

claude:
  api_key: ${ANTHROPIC_API_KEY}
  model: claude-3-5-sonnet-latest
  max_tokens: 4096
  temperature: 0.2

grok:
  api_key: ${GROK_API_KEY}
  model: grok-2-latest
  max_tokens: 4096
  temperature: 0.2